export const ERROR = {
  INTERNAL_SERVER_ERROR: { code: 500, message: "Internal Server Error" },
  USER_NOT_FOUND: { code: 404, message: "User not found" },
  USER_ALREADY_DELETED: { code: 410, message: "User already deleted" },
  EMAIL_ALREADY_EXISTS: { code: 409, message: "Email already exists" },
  POST_NOT_FOUND: { code: 404, message: "Post not found" },
  POST_ALREADY_DELETED: { code: 410, message: "Post already deleted" },
  INVALID_CREDENTIALS: { code: 401, message: "Invalid email or password" },
  INVALID_LOGIN: { code: 401, message: "Invalid email or password" },
  INVALID_REFRESH_TOKEN: {
    code: 401,
    message: "Invalid or expired refresh token",
  },
  VALIDATION_ERROR: { code: 400, message: "Validation error" },
  BAD_REQUEST: { code: 400, message: "Bad request" },
  FORBIDDEN: { code: 403, message: "Forbidden" },
  ACCESS_DENIED: { code: 403, message: "Access denied" },
  UNAUTHORIZED: { code: 401, message: "Unauthorized access" },
  TOKEN_EXPIRED: { code: 401, message: "Token expired" },
  INVALID_TOKEN: { code: 401, message: "Invalid token" },
  RESOURCE_CONFLICT: { code: 409, message: "Resource conflict" },
  PASSWORD_TOO_WEAK: { code: 400, message: "Password too weak" },
  FILE_TOO_LARGE: { code: 413, message: "File too large" },
  UNSUPPORTED_FILE_TYPE: { code: 415, message: "Unsupported file type" },
  DB_ERROR: { code: 500, message: "Database error" },
  EXTERNAL_API_ERROR: { code: 502, message: "External API error" },
  RATE_LIMIT_EXCEEDED: { code: 429, message: "Too many requests" },
  NOT_IMPLEMENTED: { code: 501, message: "Not implemented" },
  RESOURCE_NOT_FOUND: { code: 404, message: "Resource not found" },
};
